# Generated by Django 2.2.2 on 2019-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190630_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='单词')),
                ('alphabet', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('voice', models.CharField(max_length=255)),
                ('word_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '词汇',
            },
        ),
    ]
