# Generated by Django 2.2.2 on 2019-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20190702_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='imag',
            field=models.ImageField(null=True, upload_to='imag_folder/', verbose_name='图片'),
        ),
    ]
