# Generated by Django 2.2.2 on 2019-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_strangeword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clockingdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('clock_day_count', models.CharField(max_length=255, verbose_name='打卡天数')),
                ('word_total_count', models.CharField(max_length=255, verbose_name='记单词总数')),
            ],
            options={
                'verbose_name': '打卡数据',
                'verbose_name_plural': '打卡数据',
            },
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='clock_day_count',
        ),
    ]
